[config]
default_to_workspace = false

[env]
CARGO_MAKE_CLIPPY_ARGS = "-- --no-deps"
CARGO_MAKE_FORMAT_TOML_FILES = "*.toml"
CARGO_MAKE_COVERAGE_PROVIDER = "llvm-cov"
CARGO_MAKE_RUN_TOML_FORMAT = true
CARGO_MAKE_SKIP_SLOW_SECONDARY_FLOWS = true

[tasks.dev-test-flow]
dependencies = [
  "format-flow",
  "format-toml-conditioned-flow",
  "clippy-flow",
  "build-flow",
  "docs-flow",
  "test-flow",
]

[tasks.pre-build]
dependencies = ["sort-ci", "unused-dependencies-flow"]

[tasks.ci-flow]
dependencies = [
  "pre-ci-flow",
  "print-env-flow",
  "check-format-flow",
  "clippy-flow",
  "build-flow",
  "docs-flow",
  "test-flow",
  "coverage-flow",
  "post-ci-flow",
]

[tasks.test]
workspace = true
description = "Run our test suite"
command = "cargo"
args = [
  "nextest",
  "run",
  "--locked",
  "@@remove-empty(CARGO_MAKE_CARGO_VERBOSE_FLAGS)",
  "@@split(CARGO_MAKE_CARGO_BUILD_TEST_FLAGS, )",
]

[tasks.help]
command = "cargo"
description = "List help text for wack executable"
category = "Development"
args = [
  "run",
  "@@remove-empty(CARGO_MAKE_CARGO_VERBOSE_FLAGS)",
  "@@split(CARGO_MAKE_CARGO_BUILD_TEST_FLAGS, )",
  "--",
  "--help",
]

[tasks.outdated]
workspace = true
description = "List dependencies with newer released versions"
args = ["outdated", "--root-deps-only", "--exit-code", "1"]

[tasks.fmt]
workspace = true
alias = "format"

[tasks.check-format]
workspace = true

[tasks.wc]
description = "Calculate the LoC in src."
category = "Development"
command = "tokei"
args = ["."]

[tasks.sort-ci]
description = "Assert that Cargo.toml is sorted."
category = "Development"
command = "cargo"
args = ["sort", "--check"]

[tasks.sort]
description = "Sort Cargo.toml"
category = "Development"
command = "cargo"
args = ["sort"]

[tasks.bacon]
description = "Watch tests and rerun on file change."
category = "Development"
command = "bacon"
args = [
  "nextest",
  "--",
  "--lib",
  "@@split(CARGO_MAKE_CARGO_BUILD_TEST_FLAGS, )",
]
