workspace = "robbie"
application = "mckinstry"
config.monitor.aws-cloudwatch = {}

[config.ingress.aws-api-gateway]
stage-name = "foo"
gateway-name = "bar"
resource-path = "baz"
resource-method = "pop"
region = "fizz"

[config.platform.aws-lambda]
name = "buzz"
region = "fizz"
