[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.load-gatewayclass]
description = "Load a development gateway class into the cluster"
command = "kubectl"
args = ["apply", "-f", "./gatewayclass.yml"]

[tasks.unload-gatewayclass]
description = "Unload the development gateway class"
command = "kubectl"
args = [
  "delete",
  "gatewayclasses.gateway.networking.k8s.io",
  "multitool-gateway-class",
]
