name: "On Push – Validate Build"

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  # TODO: Exfiltrate this job into one or more action/jobs so it can be reused
  #       for on-pr and on-merge.
  # This job installs Cargo Make and Cargo Nextest before running
  # the CI workflow using Cargo Make. Most of the time, it should
  # restore Cargo Make and other dependencies from cache.
  build:
    name: Validate Rust Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v4

      - name: "Install Rust (Stable)"
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview,rustfmt,clippy
     
      - name: "Restore Rust Cache"
        uses: Swatinem/rust-cache@v2
      
      - name: "Install Cargo Tools from Binaries."
        uses: "taiki-e/install-action@v2"
        with:
          tool: "cargo-tarpaulin,cargo-make,cargo-nextest,cargo-llvm-cov"

      - name: "Install Cargo Sort"
        uses: taiki-e/cache-cargo-install-action@v1
        with:
          tool: cargo-sort

      - name: "Install Taplo CLI"
        uses: taiki-e/cache-cargo-install-action@v1
        with:
          tool: taplo-cli
      
      - name: "Cargo Make"
        run: cargo make ci-flow
